spring.application.name: api-gateway
server.port: 8080

---
management.tracing:
  enabled: true
  observation:
    enabled: true
  sampling.probability: 1.0

tracing:
  url: http://localhost:4317
logging.pattern.level: "[${spring.application.name:} trace_id=%X{traceId:-} span_id=%X{spanId:-}] %p"
---
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        instanceZone: bank-app
        register: false
        registerHealthCheck: false
        tags: api-gateway
      config:
        enabled: false
        retry:
          enabled: true
          initialInterval: 2
---
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            maxAge: 3600
---
spring:
  cloud:
    gateway:
      routes:
        - id: bank-app
          uri: lb://bank-app
          predicates:
            - Path=/bank/**
          filters:
            - RewritePath=/bank/(?<segment>.*), /$\{segment}
