[versions]
springBoot = "3.2.5"
springDependencyManagement = "1.1.4"
aeronVersion = "1.44.1"
sbeVersion = "1.31.1"
agronaVersion = "1.21.1"
slf4jVersion = "2.0.9"
logbackVersion = "1.4.14"
picocliVersion = "4.7.5"
jlineVersion = "3.24.1"
picoJlineVersion = "4.7.5"

[libraries]
aeron = { group = "io.aeron", name = "aeron-all", version.ref = "aeronVersion" }
agrona = { group = "org.agrona", name = "agrona", version.ref = "agronaVersion" }
sbe = { group = "uk.co.real-logic", name = "sbe-tool", version.ref = "sbeVersion" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4jVersion" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logbackVersion" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocliVersion" }
jline = { group = "org.jline", name = "jline", version.ref = "jlineVersion" }
picoJline = { group = "info.picocli", name = "picocli-shell-jline3", version.ref = "picoJlineVersion" }
