spring.application.name: cluster

---
management.tracing:
  enabled: true
  sampling.probability: 1.0

tracing:
  url: http://localhost:4317
logging.pattern.level: "[${spring.application.name:} trace_id=%X{traceId:-} span_id=%X{spanId:-}] %p"
---
logging:
  level:
    root: INFO
    'gc.garcol.bankcluster': DEBUG

aeron:
  cluster:
    hosts: ${CLUSTER_ADDRESSES:localhost} # separate by ','. Example: "127.0.0.1,127.0.0.2,127.0.0.3"
    port: ${CLUSTER_PORT_BASE:9000}
    node: ${CLUSTER_NODE:0}
    baseDir: ${BASE_DIR:./node0}
    dnsDelay: ${DNS_DELAY:false}
