spring.application.name: cluster

---
management.tracing:
  enabled: true
  sampling.probability: 1.0

tracing:
  url: http://localhost:4317
logging:
  pattern.correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  include-application-name: false
---
logging:
  level:
    root: INFO
    'gc.garcol.bankcluster': DEBUG

aeron:
  cluster:
    hosts: ${CLUSTER_ADDRESSES:localhost} # separate by ','. Example: "127.0.0.1,127.0.0.2,127.0.0.3"
    port: ${CLUSTER_PORT_BASE:9000}
    node: ${CLUSTER_NODE:0}
    baseDir: ${BASE_DIR:./node0}
    clusterDir: ${aeron.cluster.baseDir}/cluster
    dnsDelay: ${DNS_DELAY:false}
