spring.application.name: bank-app
server:
  host: ${SERVER_HOST:localhost}
  port: ${SERVER_PORT:8000}
---
cluster:
  host: ${CLUSTER_HOST:localhost} # separate by ','. Example: "127.0.0.1,127.0.0.2,127.0.0.3"
  port: ${CLUSTER_PORT:9000}
---
logging:
  level:
    root: INFO
    'gc.garcol.bankapp': DEBUG
